# Generated by Django 5.2.4 on 2025-10-03 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('requirement_file', models.FileField(blank=True, null=True, upload_to='files/pdf/')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.CharField(choices=[('diploma', 'Diploma'), ('degree', 'Degree')], default='diploma', max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.category')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('national_id', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_photo', models.FileField(blank=True, null=True, upload_to='images/passport_photos/')),
                ('qualification', models.TextField(blank=True, null=True)),
                ('academic_transcript', models.FileField(blank=True, null=True, upload_to='files/pdf/')),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('personal_statement', models.FileField(blank=True, null=True, upload_to='files/pdf/')),
                ('recommendation', models.FileField(blank=True, null=True, upload_to='files/pdf/')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_applications', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(limit_choices_to={'role': 'university'}, on_delete=django.db.models.deletion.CASCADE, related_name='university_applications', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courses')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='UniversityCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_slots', models.IntegerField(default=0)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courses')),
                ('university', models.ForeignKey(limit_choices_to={'role': 'university'}, on_delete=django.db.models.deletion.CASCADE, related_name='university_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'University course',
                'verbose_name_plural': 'University courses',
            },
        ),
    ]
