# Generated by Django 5.2.4 on 2025-09-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_university_created_at_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
