# Generated by Django 5.2.4 on 2025-09-13 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_courses_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='address',
        ),
    ]
