# Generated by Django 5.2.4 on 2025-09-14 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_university_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='university',
            field=models.ForeignKey(limit_choices_to={'role': 'university'}, on_delete=django.db.models.deletion.CASCADE, related_name='university_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
