# Generated by Django 5.2.4 on 2025-09-16 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_application_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='courses',
        ),
        migrations.AlterField(
            model_name='universitycourses',
            name='university',
            field=models.ForeignKey(limit_choices_to={'role': 'university'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
