# Generated by Django 5.2.4 on 2025-09-14 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_customuser_address'),
        ('core', '0004_remove_university_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.category'),
        ),
    ]
